Update AnsiblePipline.yml

diff --git a/.github/workflows/AnsiblePipline.yml b/.github/workflows/AnsiblePipline.yml
--- a/.github/workflows/AnsiblePipline.yml
+++ b/.github/workflows/AnsiblePipline.yml
@@ -13,18 +13,16 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v3
 
-  
-      - name: Test DNS resolution
-        run: |
-          ping -c 3 ${{ secrets.VCENTER_HOST }} || echo "Cannot resolve host"
-
-
       - name: Set up Ansible
         run: |
             sudo apt-get update
             sudo apt-get install -y ansible python3-pip
             pip3 install requests pyvmomi
             ansible-galaxy collection install community.vmware
+      
+      - name: Test DNS resolution
+        run: |
+            ping -c 3 ${{ secrets.VCENTER_HOST }} || echo "Cannot resolve host"
 
 
       - name: Run Ansible Playbook
